### ISSUE TITLE
Enhancement: refresh or reload button(s) to reload JSON(s) from disk

### ISSUE THREAD

**Issue by mcarans** [coozoo/qtjsondiff#10]
Thanks for a super useful utility!

I would like to suggest adding a button that forces the reload of the JSON file in the "JSON View" and 2 buttons in the "Compare View" one for each JSON file to force reloading of that particular file.

**Comment by coozoo** [comment]
You're welcome.
Yes I have Idea to do that, because sometimes lazy to hit ENTER.
Just for info if you didn't find it yet if cursor in address/path line edit it will reload file when you hit ENTER :)
And yeah once it will be added to json view it will be added automatically to compare view :) it's the same widget.
I will try to add it a bit later

**Comment by mcarans** [comment]
Thanks for the advice. Will it reload when you hit ENTER even if you do not change the path in the address/path line?

**Comment by coozoo** [comment]
> Thanks for the advice. Will it reload when you hit ENTER even if you do not change the path in the address/path line?

yep, it will be reloaded :) I'm usually using it for URLs but no matter is it path or url

**Comment by coozoo** [comment]
Aded 45c604bf9f2151396d0a958ff1732c08d1697ab6
