### ISSUE TITLE
Jump to next/previous difference

### ISSUE THREAD

**Issue by mcarans** [coozoo/qtjsondiff#17]
It would be super if there were buttons to jump to next/previous difference when the scrolls are synced.

**Comment by coozoo** [comment]
added some navigation in 5380fe1 
soon I will merge it to master

**Comment by mcarans** [comment]
It looks great. The only thing is that it seems to jump to the parent node of a differing node then to the differing node which slows the navigation. If there were many levels, I think it would be a bit slow. Perhaps it should just go straight to the differing node only not the parent (although I think a separate jump to parent button might be useful for any node regardless of whether it is being compared with another).

**Comment by coozoo** [comment]
@mcarans I think in your case parent simply contains different object 
so such logic suppose that those objects are different....
For example screen below
here support selected because it contains different item so object itself is different
![image](https://user-images.githubusercontent.com/25594311/105089211-7e4cd400-5aa5-11eb-8b98-3adf01fc15fd.png)

actually I agree that maybe it's better to exclude such difference but I'm not sure 
Do you think It's better to exclude "yellow" difference?

**Comment by mcarans** [comment]
@coozoo Ah, I see. I think it's better to either exclude yellow differences or make it configurable and exclude yellow differences by default.

**Comment by coozoo** [comment]
Here changes to browse elements only without object/arrays

77a0948e00111a67a4f95eba37986bc25f57977b
