### ISSUE TITLE
alpha for colors has been disabled for some reason

### ISSUE THREAD

**Issue by pvanek** [coozoo/qtjsondiff#23]
why? What exactly is affected?
```
// disable temporary because using alpha affects to "fast" comparison logic and needs some handling there
```

**Comment by coozoo** [comment]
@pvanek because it makes broken fast comparison mode :)

I swear I tested this commit. But missed one detail (and I didn't knew that)  alpha modifying original colors when you requesting them by getcolor. In this logic I'm using color codes (from constants) as indicator what type of difference there. As result such comparison by whole path sopped working. I need to find some trick  to do here. Additionally I have plans to make color as property and configurable....
